# Generated by Django 2.1.7 on 2019-02-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190225_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedra',
            name='catedra_dias',
            field=models.CharField(default='dias', max_length=250),
            preserve_default=False,
        ),
    ]
