# Generated by Django 2.1.7 on 2019-02-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190225_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='catedra_days',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
