# Generated by Django 2.1.7 on 2019-02-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190225_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='catedra_comision',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='catedra',
            name='catedra_horario',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='catedra',
            name='catedra_materia',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='catedra',
            name='catedra_nombre',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
