# Generated by Django 2.1.7 on 2019-03-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190225_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedra',
            name='catedra_area',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='catedra',
            name='catedra_int',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='catedra',
            name='catedra_periodo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='catedra',
            name='catedra_puntos',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
